version: "3.7"
services:
  app-bancaire:
    build:
      context: ./backend_bancaire
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - "db-bancaire"
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring

  db-bancaire:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: bancaire
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    restart: always

  phpmyadmin-bancaire:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - "db-bancaire"
    environment:
      PMA_HOST: db-bancaire
      MYSQL_ROOT_PASSWORD: spring

  app-iban:
    build:
      context: ./backend_iban
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    restart: always
