version: "3.7"
services:
  app-bancaire:
    build:
      context: ./backend_bancaire
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - "db-bancaire"
      - "rabbitmq"
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring
      SPRING_RABBITMQ_HOST: rabbitmq

  db-bancaire:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: bancaire
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    restart: always
    security_opt:
      - seccomp:unconfined

  phpmyadmin-bancaire:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - "db-bancaire"
    environment:
      PMA_HOST: db-bancaire
      MYSQL_ROOT_PASSWORD: spring

  app-iban:
    build:
      context: ./backend_iban
      dockerfile: Dockerfile
    depends_on:
      - "rabbitmq"
    ports:
      - "8085:8085"
    restart: always

  app-transaction:
    build:
      context: ./backend_transaction
      dockerfile: Dockerfile
    depends_on:
      - "rabbitmq"
    ports:
      - "8086:8086"
    restart: always

  rabbitmq:
    image: rabbitmq:3.9.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
